### ISSUE TITLE
SPARSE (Редки?) матрици в Python

### ISSUE THREAD

**Issue by nikola126** [auto-ml-squad/regression#6]
Как се създават sparse матрици в Python ?

Изглежда, че в кода от Matlab всякакви sparse матрици се преобразуват в пълни/нормални в някакъв момент.
Как да се "пресъздаде" sparse матрица в пълна в Python така, че да е аналогична на тази в Matlab?

![image](https://user-images.githubusercontent.com/18590016/63528622-f0fdfc80-c50b-11e9-948d-77497172e617.png)
![image](https://user-images.githubusercontent.com/18590016/63529245-0c1d3c00-c50d-11e9-8876-91136500d976.png)

**Comment by nikola126** [comment]
Избягва се използването на sparse/редки матрици в _main_lspv_ .

**Comment by efremov1** [comment]
Здравей, Ники,

Sparse (на БГ разредени) матрици се формират в dmpv() и се ползват в lspv.
Защо трябва да се избягва ползването на тези матрици?


На пн, 26 авг 2019 г., 15:25 nikola126 <notifications@github.com> написа:

**Comment by nikola126** [comment]
Прочетох на няколко места, че се използват с цел пестене на място ( и може би по-лесни изчисления) , ако голям процент от матрицата представлява нули, като се създава само указател за клетките на матрицата които не са нули. 
Не бях сигурен дали ще успея да намеря правилните команди за да ги пресъздам по същия начин по който са създадени в Matlab и затова не ги ползвах изобщо.
Като цяло се старая да получавам същите резултати и успях и без тези редки матрици, затова и написах че "избягвам" ползването им.
