### ISSUE TITLE
PV2M.m стъпки

### ISSUE THREAD

**Issue by nikola126** [auto-ml-squad/regression#7]
**Файлът създава матрица на параметрите от вектор на параметрите.**

Как точно работи този файл?
Има ли **точна формула**, която следва докато подрежда стойностите в матрица? 

За файловете различни от _MAIN_LSPV_, _MAIN_LSPM_ и _MAIN_WLSPV_, преминаването към Python е невъзможно, докато този файл ще трябва да се преработи така, че да работи нормално и да следва някаква логика.

**Comment by efremov1** [comment]
Няма формула, а се следва логиката, че (напр. за ARX модел) матрицата и векторът на параметриет са:
Tita = [A1 A2 ... Ana B1 B2 ... Bnb]', Ai, Bj - матрици
tita = [a11,1 ... a11,na11 a12,1 ... a12,na12 ... b11,1 b11,nb11 ...]'
Та като знаем тази структура на Tita и tita можем да пренаредим параметрите от вектор в матрица и обратното. Когато степените naij и bnij на отделните полиноми са различни, тогава при прехода от tita къв Tita трябва да добавим 0-ли и това се случва в pv2m.
