### ISSUE TITLE
Грешки в поелементно умножение на матрици

### ISSUE THREAD

**Issue by nikola126** [auto-ml-squad/regression#8]
**Грешки в умножението на матрици.
Разлики в резултатите между Python и Matlab.**

Когато сметките се изпълняват една по една, резултатите са същите, но ако се вкарат в цикъл и се запомнят в променлива се получават или силно закръглени (до цели числа) или грешни резултати.

![matlab_multiplication](https://user-images.githubusercontent.com/18590016/64113985-77c89a00-cd94-11e9-8092-2ebf8b146e5a.jpg)

![spyder_multiplication](https://user-images.githubusercontent.com/18590016/64113986-77c89a00-cd94-11e9-9deb-4d058883c00b.jpg)

**Comment by efremov1** [comment]
Закръглението в питон ли е? Гледам от тел. не успявам да се ориентирам...

На пн, 2 сеп 2019 г., 15:36 nikola126 <notifications@github.com> написа:

**Comment by nikola126** [comment]
Да, сега виждам че матриците между Matlab и python не са съвсем еднакви, но ми направи впечатление как го закръгля или към 1 или към -1.
Ще се опитам да ги пресъздам само тези матрици които се виждат, защото целия код няма да мога, но си спомням, че пробвах поелементно се получават по-близки резултати с тези от матлаб

**Comment by nikola126** [comment]
Сигурно нещо моментно се е объркало, защото сега пробвах да ги пресъздам само клетките които се виждат в снимката и се получиха верните сметки.
Може би има значение данните как се запомнят от numpy, защото като ги въведа ръчно се смятат правилно.

**Comment by efremov1** [comment]
Супер, че се е отправила работата. Понякога заради разни типове и дейта
структури стойностите се променят, но не знам заради какво точно се е
получавал предишният резултат...

На пн, 2 сеп 2019 г., 16:43 nikola126 <notifications@github.com> написа:
